spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mystudentdb?createDatabaseIfNotExist=true
    username: root
    password: admin
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        id:
          new_generator_mappings: false

server:
   port: 8080 # This is the default port anyway, but you can change it here

logging:
  io:
    swagger:
      models:
        parameters:
          AbstractSerializableParameter: error
          
security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 300000 # 5min (5*60*1000ms)
      
UserController:
  signin: Authenticates user and returns its JWT token.
  signup: Creates user and returns its JWT token
  delete: Deletes specific user by username
  search: Returns specific user by username
  me: Returns current user's data
  
StudentController:
  create: Create New Student
  update: Update specific student by id
  delete: Delete specific student by id
  findById: Find specific student by id
  findAll: Find all students