# active db settng ; mail setting
spring:

  profiles:
    active: posgresql

  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15

  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: mytestmail.aabbcc@gmail.com
    password: hdnemiojgfaxkcvn
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
    protocol: smtp
    test-connection: false

    
# common 
server:
   port: 8080 
   
logging:
  io:
    swagger:
      models:
        parameters:
          AbstractSerializableParameter: error

security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 300000 # 5min (5*60*1000ms)

HomeController:
  test: Test
  sendEmail: Sent Mail

UserController:
  signin: Authenticates user and returns its JWT token.
  signup: Creates user and returns its JWT token
  delete: Deletes specific user by username
  search: Returns specific user by username
  me: Returns current user's data
  
StudentController:
  create: Create New Student
  update: Update specific student by id
  delete: Delete specific student by id
  findById: Find specific student by id
  findAll: Find all students
  findPaginated: Find all paginated students